version: '3.8'

services:
  # PostgreSQL para o serviço de pedidos
  postgres-pedidos:
    image: postgres:13
    volumes:
      - postgres_pedidos_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pedidos
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pedidos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL para o serviço de almoxarifado
  postgres-almoxarifado:
    image: postgres:13
    volumes:
      - postgres_almoxarifado_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=almoxarifado
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d almoxarifado"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ para comunicação entre serviços
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço de Pedidos
  pedido-service:
    build: 
      context: ./pedido_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-pedidos:5432/pedidos
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres-pedidos
      - rabbitmq
    restart: on-failure

  # Serviço de Almoxarifado
  almoxarifado-service:
    build: 
      context: ./almoxarifado_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-almoxarifado:5432/almoxarifado
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres-almoxarifado
      - rabbitmq
    restart: on-failure

volumes:
  postgres_pedidos_data:
  postgres_almoxarifado_data:
  rabbitmq_data:
